import{i as c,S as u}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d="https://pixabay.com/api/",p="45141895-b62da3b06f4b18f1184207a2c";function m(s){const o=new URLSearchParams({key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${d}?${o}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function f(s,o){if(o.innerHTML="",s.hits.length===0){c.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}s.hits.forEach(t=>{const n=document.createElement("li");n.classList.add("gallery-item-wrapper");const e=document.createElement("a");e.href=t.largeImageURL,e.classList.add("gallery-item");const r=document.createElement("img");r.classList.add("img"),r.src=t.webformatURL,r.alt=t.tags;const i=document.createElement("div");i.classList.add("container-properties"),i.innerHTML=`
            <ul class="list-properties">
                <li class="properties"><p class="text"><strong>Likes</strong> ${t.likes}</p></li>
                <li class="properties"><p class="text"><strong>Views</strong> ${t.views}</p></li>
                <li class="properties"><p class="text"><strong>Comments</strong> ${t.comments}</p></li>
                <li class="properties"><p class="text"><strong>Downloads</strong> ${t.downloads}</p></li>
            </ul>
        `,e.appendChild(r),e.appendChild(i),n.appendChild(e),o.appendChild(n)}),lightbox?lightbox.refresh():lightbox=new u(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}const h=document.querySelector(".form"),a=document.querySelector(".search"),g=document.querySelector(".btn"),l=document.querySelector(".loader"),y=document.querySelector(".gallery");a.addEventListener("input",w);h.addEventListener("submit",E);function L(){l.style.display="block"}function b(){l.style.display="none"}function w(){g.disabled=a.value.trim()===""}function E(s){s.preventDefault();const o=a.value.trim();if(o===""){iziToast.error({title:"Error",message:"Please enter a search query.",timeout:3e3,position:"topRight"});return}L(),m(o).then(t=>{f(t,y)}).catch(t=>{iziToast.error({title:"Error",message:"An error occurred while fetching images. Please try again!",timeout:3e3,position:"topRight"})}).finally(()=>{b()})}
//# sourceMappingURL=commonHelpers.js.map
